services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: PetFriends
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - petFriends

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: tauber
      RABBITMQ_DEFAULT_PASS: secret
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - petFriends

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - '9411:9411'
    networks:
      - petFriends

  PetFriendsOrder:
    image: petfriends-order
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - petFriends
    deploy:
        replicas: 1

  PetFriendsInventory:
    image: petfriends-inventory
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - PetFriendsOrder
    networks:
      - petFriends
    deploy:
        replicas: 1

  PetFriendsTransport:
    image: petfriends-transport
    ports:
      - '8082:8082'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - PetFriendsInventory
    networks:
      - petFriends
    deploy:
        replicas: 1

networks:
  petFriends:
    driver: bridge

